// ---- Rythu Bazars (locations approximate — verify on ground) ----
const BAZARS = [
  { id: "erragadda",       en: "Erragadda Rythu Bazar",       te: "ఎర్రగడ్డ రైతు బజార్",        lat: 17.4565, lng: 78.4340 },
  { id: "mehdipatnam",     en: "Mehdipatnam Rythu Bazar",     te: "మెహదీపట్నం రైతు బజార్",      lat: 17.3948, lng: 78.4360 },
  { id: "kukatpally",      en: "Kukatpally Rythu Bazar",      te: "కూకట్‌పల్లి రైతు బజార్",       lat: 17.4849, lng: 78.4110 },
  { id: "falaknuma",       en: "Falaknuma Rythu Bazar",       te: "ఫలక్‌నుమా రైతు బజార్",        lat: 17.3317, lng: 78.4646 },
  { id: "saroornagar",     en: "Saroornagar Rythu Bazar",     te: "సరూర్‌నగర్ రైతు బజార్",       lat: 17.3556, lng: 78.5262 },
  { id: "vanasthalipuram", en: "Vanasthalipuram Rythu Bazar", te: "వనస్థలిపురం రైతు బజార్",     lat: 17.3373, lng: 78.5576 },
  { id: "alwal",           en: "Alwal Rythu Bazar",           te: "అల్వాల్ రైతు బజార్",          lat: 17.5049, lng: 78.5093 },
  { id: "kushaiguda",      en: "Kushaiguda Rythu Bazar",      te: "కుషాయిగూడ రైతు బజార్",       lat: 17.4829, lng: 78.5806 },
  { id: "gudimalkapur",    en: "Gudimalkapur Market",         te: "గుడిమల్కాపూర్ మార్కెట్",      lat: 17.3873, lng: 78.4295 },
  { id: "meerpet",         en: "Meerpet Rythu Bazar",         te: "మీర్‌పేట్ రైతు బజార్",         lat: 17.3196, lng: 78.5334 },
  { id: "serilingampally", en: "Serilingampally Rythu Bazar", te: "శేరిలింగంపల్లి రైతు బజార్",    lat: 17.4931, lng: 78.3416 },
  { id: "rkpuram",         en: "RK Puram Rythu Bazar",        te: "ఆర్.కె.పురం రైతు బజార్",      lat: 17.4776, lng: 78.5416 },
];
const BAZAR_TIMINGS = { en: "6:00 AM – 8:00 PM, all days", te: "ఉదయం 6 – రాత్రి 8, అన్ని రోజులు" };

// ---- Proposed Collection Points on major highways into Hyderabad ----
// bazarId = destination rythu bazar the pooled vehicle delivers to
const COLLECTION_POINTS = [
  { id: "medchal",    en: "Medchal Collection Point",    te: "మేడ్చల్ సేకరణ కేంద్రం",     lat: 17.6297, lng: 78.4814, hwyEn: "NH-44 (Nagpur Highway)",       hwyTe: "ఎన్‌హెచ్-44 (నాగ్‌పూర్ హైవే)",      bazarId: "alwal" },
  { id: "shamirpet",  en: "Shamirpet Collection Point",  te: "షామీర్‌పేట్ సేకరణ కేంద్రం",  lat: 17.5946, lng: 78.5766, hwyEn: "Rajiv Rahadari (Karimnagar Rd)", hwyTe: "రాజీవ్ రహదారి (కరీంనగర్ రోడ్)", bazarId: "kushaiguda" },
  { id: "gajwel",     en: "Gajwel Collection Point",     te: "గజ్వేల్ సేకరణ కేంద్రం",     lat: 17.8510, lng: 78.6830, hwyEn: "Rajiv Rahadari (Siddipet Rd)",  hwyTe: "రాజీవ్ రహదారి (సిద్దిపేట రోడ్)",  bazarId: "kushaiguda" },
  { id: "ghatkesar",  en: "Ghatkesar Collection Point",  te: "ఘట్‌కేసర్ సేకరణ కేంద్రం",   lat: 17.4507, lng: 78.6857, hwyEn: "NH-163 (Warangal Highway)",    hwyTe: "ఎన్‌హెచ్-163 (వరంగల్ హైవే)",      bazarId: "kushaiguda" },
  { id: "choutuppal", en: "Choutuppal Collection Point", te: "చౌటుప్పల్ సేకరణ కేంద్రం",   lat: 17.2528, lng: 78.8768, hwyEn: "NH-65 (Vijayawada Highway)",   hwyTe: "ఎన్‌హెచ్-65 (విజయవాడ హైవే)",     bazarId: "vanasthalipuram" },
  { id: "kandukur",   en: "Kandukur Collection Point",   te: "కందుకూర్ సేకరణ కేంద్రం",    lat: 17.1085, lng: 78.4728, hwyEn: "Srisailam Highway",            hwyTe: "శ్రీశైలం హైవే",                bazarId: "saroornagar" },
  { id: "shadnagar",  en: "Shadnagar Collection Point",  te: "షాద్‌నగర్ సేకరణ కేంద్రం",   lat: 17.0895, lng: 78.2181, hwyEn: "NH-44 (Bangalore Highway)",    hwyTe: "ఎన్‌హెచ్-44 (బెంగళూరు హైవే)",     bazarId: "falaknuma" },
  { id: "chevella",   en: "Chevella Collection Point",   te: "చేవెళ్ల సేకరణ కేంద్రం",     lat: 17.3113, lng: 78.1360, hwyEn: "Chevella–Vikarabad Road",      hwyTe: "చేవెళ్ల–వికారాబాద్ రోడ్",        bazarId: "mehdipatnam" },
  { id: "patancheru", en: "Patancheru Collection Point", te: "పటాన్‌చెరు సేకరణ కేంద్రం",  lat: 17.5333, lng: 78.2645, hwyEn: "NH-65 (Mumbai Highway)",       hwyTe: "ఎన్‌హెచ్-65 (ముంబై హైవే)",       bazarId: "kukatpally" },
  { id: "sangareddy", en: "Sangareddy Collection Point", te: "సంగారెడ్డి సేకరణ కేంద్రం",   lat: 17.6248, lng: 78.0866, hwyEn: "NH-65 (Mumbai Highway)",       hwyTe: "ఎన్‌హెచ్-65 (ముంబై హైవే)",       bazarId: "erragadda" },
];

// ---- Produce catalog (vegetables, leafy greens, fruits, staples) ----
const PRODUCE = [
  { id: "tomato",      en: "Tomato",          te: "టమాటా",          emoji: "🍅" },
  { id: "onion",       en: "Onion",           te: "ఉల్లిపాయ",        emoji: "🧅" },
  { id: "brinjal",     en: "Brinjal",         te: "వంకాయ",          emoji: "🍆" },
  { id: "okra",        en: "Okra",            te: "బెండకాయ",         emoji: "🌿" },
  { id: "bottlegourd", en: "Bottle gourd",    te: "సొరకాయ",         emoji: "🥒" },
  { id: "ridgegourd",  en: "Ridge gourd",     te: "బీరకాయ",          emoji: "🥒" },
  { id: "bittergourd", en: "Bitter gourd",    te: "కాకరకాయ",         emoji: "🥒" },
  { id: "snakegourd",  en: "Snake gourd",     te: "పొట్లకాయ",        emoji: "🥒" },
  { id: "cucumber",    en: "Cucumber",        te: "దోసకాయ",          emoji: "🥒" },
  { id: "pumpkin",     en: "Pumpkin",         te: "గుమ్మడికాయ",       emoji: "🎃" },
  { id: "greenchilli", en: "Green chilli",    te: "పచ్చిమిర్చి",       emoji: "🌶️" },
  { id: "capsicum",    en: "Capsicum",        te: "క్యాప్సికం",        emoji: "🫑" },
  { id: "potato",      en: "Potato",          te: "బంగాళదుంప",       emoji: "🥔" },
  { id: "carrot",      en: "Carrot",          te: "క్యారెట్",          emoji: "🥕" },
  { id: "beetroot",    en: "Beetroot",        te: "బీట్‌రూట్",         emoji: "🟣" },
  { id: "radish",      en: "Radish",          te: "ముల్లంగి",         emoji: "⚪" },
  { id: "cabbage",     en: "Cabbage",         te: "క్యాబేజీ",          emoji: "🥬" },
  { id: "cauliflower", en: "Cauliflower",     te: "కాలీఫ్లవర్",        emoji: "🥦" },
  { id: "beans",       en: "Beans",           te: "బీన్స్",            emoji: "🫘" },
  { id: "clusterbeans",en: "Cluster beans",   te: "గోరుచిక్కుడు",      emoji: "🫛" },
  { id: "broadbeans",  en: "Broad beans",     te: "చిక్కుడుకాయ",      emoji: "🫛" },
  { id: "drumstick",   en: "Drumstick",       te: "మునగకాయ",         emoji: "🌱" },
  { id: "curryleaves", en: "Curry leaves",    te: "కరివేపాకు",        emoji: "🍃" },
  { id: "coriander",   en: "Coriander",       te: "కొత్తిమీర",         emoji: "🌿" },
  { id: "mint",        en: "Mint",            te: "పుదీనా",           emoji: "🌿" },
  { id: "spinach",     en: "Spinach (Palak)", te: "పాలకూర",          emoji: "🥬" },
  { id: "amaranth",    en: "Amaranth leaves", te: "తోటకూర",          emoji: "🥬" },
  { id: "fenugreek",   en: "Fenugreek leaves",te: "మెంతికూర",        emoji: "🥬" },
  { id: "gongura",     en: "Gongura",         te: "గోంగూర",          emoji: "🥬" },
  { id: "springonion", en: "Spring onion",    te: "ఉల్లికాడలు",       emoji: "🧅" },
  { id: "ginger",      en: "Ginger",          te: "అల్లం",            emoji: "🫚" },
  { id: "garlic",      en: "Garlic",          te: "వెల్లుల్లి",         emoji: "🧄" },
  { id: "lemon",       en: "Lemon",           te: "నిమ్మకాయ",        emoji: "🍋" },
  { id: "rawbanana",   en: "Raw banana",      te: "అరటికాయ",         emoji: "🍌" },
  { id: "banana",      en: "Banana",          te: "అరటిపండ్లు",       emoji: "🍌" },
  { id: "mango",       en: "Mango",           te: "మామిడి",          emoji: "🥭" },
  { id: "guava",       en: "Guava",           te: "జామకాయ",         emoji: "🍈" },
  { id: "papaya",      en: "Papaya",          te: "బొప్పాయి",         emoji: "🧡" },
  { id: "sweetcorn",   en: "Sweet corn",      te: "మొక్కజొన్న",       emoji: "🌽" },
  { id: "groundnut",   en: "Groundnut",       te: "వేరుశనగ",         emoji: "🥜" },
];

// ---- UI strings ----
const I18N = {
  te: {
    appName: "రైతు కనెక్ట్",
    tagline: "హైదరాబాద్ రైతు బజార్లు & సేకరణ కేంద్రాలు",
    tabMap: "మ్యాప్", tabRegister: "నమోదు", tabTransport: "రవాణా బృందాలు", tabMarket: "మార్కెట్ డిమాండ్",
    legendBazar: "రైతు బజార్", legendCP: "సేకరణ కేంద్రం (ప్రతిపాదిత)", legendFarmer: "నమోదైన రైతు",
    approxNote: "📍 స్థానాలు సుమారుగా — క్షేత్రస్థాయిలో ధృవీకరించండి",
    regTitle: "రైతు నమోదు + ఈరోజు తెచ్చే సరుకు",
    lblName: "పేరు *", lblPhone: "ఫోన్ నంబర్ *", lblScale: "రైతు రకం",
    scaleSmall: "చిన్న రైతు (< 5 ఎకరాలు)", scaleLarge: "పెద్ద రైతు",
    lblVillage: "గ్రామం పేరు *", lblMapClick: "మీ గ్రామ స్థానం — మ్యాప్‌పై నొక్కండి *",
    locNotSet: "⚠️ స్థానం ఇంకా గుర్తించలేదు", locSet: "✅ స్థానం గుర్తించబడింది",
    lblProduce: "ఈరోజు ఏమి తీసుకువస్తున్నారు? (నొక్కి ఎంచుకోండి) *",
    btnRegister: "నమోదు చేయండి",
    resultTitle: "మీ సమీప సేకరణ కేంద్రం",
    resultHint: "మ్యాప్‌పై మీ గ్రామాన్ని గుర్తించగానే సమీప కేంద్రం ఇక్కడ కనిపిస్తుంది.",
    transportTitle: "ఈరోజు రవాణా బృందాలు — కలిసి వెళ్దాం, ఖర్చు పంచుకుందాం",
    transportHint: "ఒకే సేకరణ కేంద్రానికి వచ్చే రైతులు ఒక వాహనం పంచుకుంటే ఖర్చు చాలా తగ్గుతుంది.",
    marketTitle: "ఈరోజు మార్కెట్‌కు వస్తున్న సరుకు",
    marketHint: "బజార్ నిర్వాహకులు / కొనుగోలుదారుల కోసం — ఏ కేంద్రం నుండి ఏ సరుకు ఎంత వస్తుందో చూడండి.",
    bazarDirTitle: "రైతు బజార్ల జాబితా",
    footNote: "నమూనా యాప్ — డేటా మీ బ్రౌజర్‌లో మాత్రమే నిల్వ అవుతుంది",
    nearestCP: "సమీప సేకరణ కేంద్రం", highway: "హైవే", distVillage: "మీ గ్రామం నుండి దూరం",
    destBazar: "సరుకు వెళ్లే బజార్", youSave: "ఈ ట్రిప్‌లో మీ ఆదా (సుమారు)",
    insteadOf: "హైదరాబాద్ వరకు వెళ్లే బదులు", kmCloser: "కి.మీ దగ్గర",
    farmers: "రైతులు", totalLoad: "మొత్తం బరువు", vehicle: "సూచించిన వాహనం",
    sharedCost: "పంచుకున్న ఖర్చు (ఒక్కొక్కరికి)", soloCost: "ఒంటరిగా వెళ్తే (సుమారు)",
    colFarmer: "రైతు", colVillage: "గ్రామం", colItems: "సరుకు", colKg: "కిలోలు",
    colProduce: "సరుకు", colQty: "మొత్తం (కిలోలు)", colFrom: "ఏ కేంద్రం నుండి", colFarmers: "రైతులు",
    noTrips: "ఈరోజు ఇంకా ట్రిప్‌లు నమోదు కాలేదు. నమోదు ట్యాబ్‌లో మొదటి రైతును చేర్చండి!",
    auto: "ఆటో (400 కిలోల వరకు)", tempo: "టాటా ఏస్ / టెంపో (1200 కిలోల వరకు)", truck: "మినీ ట్రక్ (1200+ కిలోలు)",
    timings: "వేళలు", regSuccess: "నమోదు విజయవంతం! రవాణా ట్యాబ్‌లో మీ బృందాన్ని చూడండి.",
    needLocation: "దయచేసి మ్యాప్‌పై మీ గ్రామ స్థానాన్ని నొక్కండి", needProduce: "దయచేసి కనీసం ఒక సరుకు ఎంచుకుని, కిలోలు నమోదు చేయండి",
    proposedCP: "ప్రతిపాదిత సేకరణ కేంద్రం", incomingToday: "ఈరోజు వస్తున్నది", nothingToday: "ఈరోజు ఏమీ నమోదు కాలేదు",
    yourVillage: "మీ గ్రామం",
    editPins: "✏️ పిన్ సరిచేయి", resetPins: "↩️ పిన్‌లను రీసెట్ చేయి",
    editPinsOn: "✏️ సరిచేసే మోడ్ ఆన్ — పిన్‌లను లాగి సరైన స్థానానికి జరపండి, ఆటోమేటిక్‌గా సేవ్ అవుతుంది",
    shareWa: "📲 వాట్సాప్‌లో బృందాన్ని పంపండి", exportCsv: "⬇️ CSV డౌన్‌లోడ్",
    waHeader: "రైతు కనెక్ట్ — ఈరోజు రవాణా బృందం", waVehicle: "వాహనం", waCostEach: "ఒక్కొక్కరికి ఖర్చు",
  },
  en: {
    appName: "Rythu Connect",
    tagline: "Hyderabad farmers' markets & collection points",
    tabMap: "Map", tabRegister: "Register", tabTransport: "Transport Groups", tabMarket: "Market Demand",
    legendBazar: "Rythu Bazar", legendCP: "Collection Point (proposed)", legendFarmer: "Registered farmer",
    approxNote: "📍 Locations approximate — verify on ground",
    regTitle: "Farmer registration + today's load",
    lblName: "Name *", lblPhone: "Phone number *", lblScale: "Farmer type",
    scaleSmall: "Small farmer (< 5 acres)", scaleLarge: "Large farmer",
    lblVillage: "Village name *", lblMapClick: "Your village location — tap on the map *",
    locNotSet: "⚠️ Location not set yet", locSet: "✅ Location set",
    lblProduce: "What are you bringing today? (tap to select) *",
    btnRegister: "Register",
    resultTitle: "Your nearest collection point",
    resultHint: "As soon as you mark your village on the map, the nearest point appears here.",
    transportTitle: "Today's transport groups — travel together, share the cost",
    transportHint: "Farmers coming to the same collection point can share one vehicle and cut costs sharply.",
    marketTitle: "Produce arriving at markets today",
    marketHint: "For bazar managers / buyers — see what produce is coming from which collection point.",
    bazarDirTitle: "Rythu Bazar directory",
    footNote: "Prototype app — data is stored only in your browser",
    nearestCP: "Nearest collection point", highway: "Highway", distVillage: "Distance from your village",
    destBazar: "Produce goes to", youSave: "Your saving this trip (approx)",
    insteadOf: "instead of travelling all the way to Hyderabad", kmCloser: "km closer",
    farmers: "farmers", totalLoad: "Total load", vehicle: "Suggested vehicle",
    sharedCost: "Shared cost (per farmer)", soloCost: "Going alone would cost (approx)",
    colFarmer: "Farmer", colVillage: "Village", colItems: "Produce", colKg: "Kg",
    colProduce: "Produce", colQty: "Total (kg)", colFrom: "From collection point", colFarmers: "Farmers",
    noTrips: "No trips registered today yet. Add the first farmer in the Register tab!",
    auto: "Auto (up to 400 kg)", tempo: "Tata Ace / Tempo (up to 1200 kg)", truck: "Mini truck (1200+ kg)",
    timings: "Timings", regSuccess: "Registered! Check your group in the Transport tab.",
    needLocation: "Please tap your village location on the map", needProduce: "Please select at least one produce item and enter kg",
    proposedCP: "Proposed collection point", incomingToday: "Arriving today", nothingToday: "Nothing registered today",
    yourVillage: "Your village",
    editPins: "✏️ Correct pins", resetPins: "↩️ Reset pins",
    editPinsOn: "✏️ Correction mode ON — drag any pin to its correct location, it saves automatically",
    shareWa: "📲 Share group on WhatsApp", exportCsv: "⬇️ Download CSV",
    waHeader: "Rythu Connect — today's transport group", waVehicle: "Vehicle", waCostEach: "Cost per farmer",
  },
};

// ---- Demo seed data (villages around Hyderabad) ----
const SEED_FARMERS = [
  { name: "రాములు / Ramulu",   phone: "9000000001", scale: "small", village: "Kallakal / కల్లకల్",     lat: 17.6650, lng: 78.4750, items: [["tomato", 120], ["brinjal", 60], ["coriander", 15]] },
  { name: "లక్ష్మి / Lakshmi",  phone: "9000000002", scale: "small", village: "Gajwel / గజ్వేల్",       lat: 17.8480, lng: 78.6790, items: [["okra", 80], ["greenchilli", 40]] },
  { name: "నర్సయ్య / Narsaiah", phone: "9000000003", scale: "small", village: "Bhuvanagiri / భువనగిరి", lat: 17.6020, lng: 78.8880, items: [["gongura", 30], ["amaranth", 25], ["tomato", 90]] },
  { name: "సైదులు / Saidulu",   phone: "9000000004", scale: "large", village: "Choutuppal / చౌటుప్పల్", lat: 17.2600, lng: 78.8700, items: [["onion", 400], ["potato", 250]] },
  { name: "యాదమ్మ / Yadamma",  phone: "9000000005", scale: "small", village: "Kandukur / కందుకూర్",   lat: 17.1100, lng: 78.4700, items: [["bottlegourd", 70], ["ridgegourd", 50], ["curryleaves", 10]] },
  { name: "మల్లేష్ / Mallesh",  phone: "9000000006", scale: "small", village: "Shadnagar / షాద్‌నగర్",  lat: 17.0850, lng: 78.2200, items: [["cucumber", 100], ["drumstick", 45]] },
  { name: "పెంటమ్మ / Pentamma", phone: "9000000007", scale: "small", village: "Chevella / చేవెళ్ల",     lat: 17.3100, lng: 78.1400, items: [["spinach", 35], ["mint", 20], ["fenugreek", 25]] },
  { name: "వెంకటేష్ / Venkatesh",phone: "9000000008", scale: "large", village: "Sangareddy / సంగారెడ్డి", lat: 17.6200, lng: 78.0900, items: [["mango", 300], ["lemon", 150], ["banana", 200]] },
  { name: "అంజయ్య / Anjaiah",   phone: "9000000009", scale: "small", village: "Dundigal / దుండిగల్",    lat: 17.5770, lng: 78.4200, items: [["cabbage", 90], ["cauliflower", 70]] },
  { name: "సరోజ / Saroja",      phone: "9000000010", scale: "small", village: "Yacharam / యాచారం",     lat: 17.1100, lng: 78.6000, items: [["tomato", 150], ["greenchilli", 30]] },
  { name: "బాలయ్య / Balaiah",   phone: "9000000011", scale: "small", village: "Kothur / కొత్తూరు",      lat: 17.1400, lng: 78.2600, items: [["okra", 60], ["brinjal", 80], ["gongura", 20]] },
  { name: "రాజేశ్వరి / Rajeswari",phone: "9000000012", scale: "small", village: "Bibinagar / బీబీనగర్",   lat: 17.4700, lng: 78.7900, items: [["snakegourd", 55], ["clusterbeans", 40], ["mint", 15]] },
];
